context:
  version: "0.9.4"

package:
  name: ls-engines
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ls-engines/-/ls-engines-${{ version }}.tgz
  sha256: 24eaf66b1f26d9f81947b344c9672b6035c5824de98115b073dfe7337b458d8a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ls-engines --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Determine if your dependency graph's stated \"engines\" criteria is met."
  homepage: https://github.com/ljharb/ls-engines
  repository: https://github.com/ljharb/ls-engines

extra:
  recipe-maintainers:
    - danielnachun
