context:
  version: "0.10.1"

package:
  name: ls-engines
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ls-engines/-/ls-engines-${{ version }}.tgz
  sha256: 63cee759f83f95f8f5530770ae965130be328d36519ed8973634896104677359

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ls-engines --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Determine if your dependency graph's stated \"engines\" criteria is met."
  homepage: https://github.com/ljharb/ls-engines
  repository: https://github.com/ljharb/ls-engines

extra:
  recipe-maintainers:
    - danielnachun
